### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by timgdavies** [kindly/flatterer-web#2]
For this JSON URL https://opendata.camden.gov.uk/api/views/9uw3-kaex/rows.json?accessType=DOWNLOAD Flatterer reports "Invalid JSON due to the following error: expected `,` or `]` at line 1 column 1844"

But running the same file through a JSON Lint Validator does not appear to throw up any errors.

**Comment by kindly** [comment]
Thanks @timgdavies this is fixed now.
